server :
  port : 8080
# spring actuator
management.endpoints.web.exposure.include: "*"

# mysql driver setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookjeok?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: bjbj
    password: bookjeok!

# jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

# thymeleaf
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false
