
# spring actuator
management.endpoints.web.exposure.include: "*"

# mysql driver setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookjeok
    username: bjbj
    password: bookjeok!

# jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
