
# spring actuator
management.endpoints.web.exposure.include: "*"

# mysql driver setting
spring:
  config.activate.on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookjeok
    username: bjbj
    password: bookjeok!

# jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

# thymeleaf
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false


---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:bookjeok;mode=mysql
    driverClassName: org.h2.Driver

  h2.console:
    enabled: false
    path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true